package frc.robot.subsystems.superstructure;

public enum Priority {
  PANIC,
  MANUAL,
  CLIMB,
  GROUND_INTAKE_CORAL,
  GROUND_VOMIT_CORAL,
  SOURCE_INTAKE_CORAL,
  SOURCE_VOMIT_CORAL,
  GROUND_INTAKE_ALGAE,
  GROUND_VOMIT_ALGAE,
  STACKED_INTAKE_ALGAE,
  STACKED_VOMIT_ALGAE,
  HANDOFF_CORAL,
  PREPARE_SCORE_ALGAE,
  PREPARE_SCORE_CORAL,
  SCORE_GAME_PIECE
}
