package frc.robot.subsystems.superstructure;

public enum Priority {
  PANIC,
  MANUAL,
  CLIMB,
  STATION_INTAKE_CORAL,
  GROUND_INTAKE_CORAL,
  GROUND_VOMIT_CORAL,
  PREPARE_SCORE_CORAL,
  SCORE_GAME_PIECE,
  HANDOFF_CORAL,
  HANDOFF_PUSH_CORAL
}
