package frc.robot.subsystems.superstructure;

public enum Priority {
  PANIC,
  MANUAL,
  CLIMB,
  GROUND_INTAKE_CORAL,
  GROUND_VOMIT_CORAL,
  STATION_INTAKE_CORAL,
  STATION_VOMIT_CORAL,
  GROUND_INTAKE_ALGAE,
  GROUND_VOMIT_ALGAE,
  STACKED_INTAKE_ALGAE,
  STACKED_VOMIT_ALGAE,
  PREPARE_SCORE_PROCESSOR,
  PREPARE_SCORE_BARGE,
  PREPARE_SCORE_CORAL,
  SCORE_GAME_PIECE,
  HANDOFF_CORAL
}
